# Base packages (core tools installed first)
base_packages=()
base_packages+=("homebrew")
base_packages+=("vim")
base_packages+=("bash")
base_packages+=("bash_it")
base_packages+=("git")

# Required packages (standard tools)
required_packages=()
required_packages+=("appgrid")
required_packages+=("bats")
required_packages+=("claude_code")
required_packages+=("claude_desktop")
required_packages+=("dock_layout")
required_packages+=("dockutil")
required_packages+=("gcc")
required_packages+=("google_chrome")
required_packages+=("iterm")
required_packages+=("jq")
required_packages+=("maccy")
required_packages+=("node")
required_packages+=("obsidian")
required_packages+=("os_prefs")
required_packages+=("pip")
required_packages+=("pycharm")
required_packages+=("python")
required_packages+=("rectangle")
required_packages+=("uv")

# Optional packages (additional tools)
optional_packages=()
optional_packages+=("1password")
optional_packages+=("1password_for_safari")
optional_packages+=("airbuddy")
optional_packages+=("aloha")
optional_packages+=("canary_mail")
optional_packages+=("chatgpt_desktop")
optional_packages+=("clean_my_mac")
optional_packages+=("disk_drill")
optional_packages+=("docker_desktop")
optional_packages+=("easeus_video_downloader")
optional_packages+=("eero")
optional_packages+=("final_cut_pro")
optional_packages+=("gnused")
optional_packages+=("goodsync")
optional_packages+=("gpg_keychain")
optional_packages+=("gradle")
optional_packages+=("imazing")
optional_packages+=("imovie")
optional_packages+=("intellij_idea")
optional_packages+=("istat_menus")
optional_packages+=("jabra_direct")
optional_packages+=("java")
optional_packages+=("jenv")
optional_packages+=("kafka")
optional_packages+=("kotlin")
optional_packages+=("ktlint")
optional_packages+=("llama_cpp")
optional_packages+=("logic_calc")
optional_packages+=("macwhisper")
optional_packages+=("mas")
optional_packages+=("microsoft_office")
optional_packages+=("microsoft_onedrive")
optional_packages+=("microsoft_teams")
optional_packages+=("moonlock")
optional_packages+=("neo4j_desktop")
optional_packages+=("ollama")
optional_packages+=("pandoc")
optional_packages+=("pcloud_drive")
optional_packages+=("pocketcas")
optional_packages+=("postgres")
optional_packages+=("relog")
optional_packages+=("remove_web_limits_for_safari")
optional_packages+=("sqlite")
optional_packages+=("swi_prolog")
optional_packages+=("topaz_video")
optional_packages+=("ultimaker_cura")
optional_packages+=("vscode")
optional_packages+=("wondershare_uniconverter")
optional_packages+=("zoom")

# Supported Node packages (installed via npm)
supported_node_packages=()

# Supported Python packages (installed via pip)
supported_pip_packages=()
