# Base packages (core tools installed first)
base_packages=()
base_packages+=("homebrew")
base_packages+=("vim")
base_packages+=("bash")
base_packages+=("bash_it")
base_packages+=("git")

# Required packages (standard tools)
required_packages=()
required_packages+=("bats")
required_packages+=("claude_code")
required_packages+=("dockutil")
required_packages+=("gcc")
required_packages+=("google_chrome")
required_packages+=("iterm")
required_packages+=("jq")
required_packages+=("maccy")
required_packages+=("node")
required_packages+=("os_prefs")
required_packages+=("pip")
required_packages+=("pycharm")
required_packages+=("python")
required_packages+=("rectangle")
required_packages+=("uv")

# Optional packages (additional tools)
optional_packages=()
optional_packages+=("docker_compose")
optional_packages+=("docker_desktop")
optional_packages+=("gnused")
optional_packages+=("gradle")
optional_packages+=("intellij_idea")
optional_packages+=("java")
optional_packages+=("jenv")
optional_packages+=("kafka")
optional_packages+=("kotlin")
optional_packages+=("ktlint")
optional_packages+=("llama_cpp")
optional_packages+=("minikube")
optional_packages+=("neo4j_desktop")
optional_packages+=("ollama")
optional_packages+=("postgres")
optional_packages+=("sqlite")

# Supported Node packages (installed via npm)
supported_node_packages=()

# Supported Python packages (installed via pip)
supported_pip_packages=()